"""Add auditing fields

Revision ID: 3adff6d93684
Revises: 52fb47eafdb9
Create Date: 2024-12-09 20:57:41.800169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3adff6d93684'
down_revision: Union[str, None] = '52fb47eafdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('case', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('case', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('case', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('organisation', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('organisation', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('organisation', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('organisation', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('organisation_user', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('organisation_user', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('organisation_user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('organisation_user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('user', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'updated_by')
    op.drop_column('user', 'created_by')
    op.drop_column('organisation_user', 'updated_at')
    op.drop_column('organisation_user', 'created_at')
    op.drop_column('organisation_user', 'updated_by')
    op.drop_column('organisation_user', 'created_by')
    op.drop_column('organisation', 'updated_at')
    op.drop_column('organisation', 'created_at')
    op.drop_column('organisation', 'updated_by')
    op.drop_column('organisation', 'created_by')
    op.drop_column('case', 'updated_at')
    op.drop_column('case', 'created_at')
    op.drop_column('case', 'updated_by')
    op.drop_column('case', 'created_by')
    # ### end Alembic commands ###
