"""Add foreign keys to case model

Revision ID: 52fb47eafdb9
Revises: 435ab419ca07
Create Date: 2024-09-25 14:58:34.407981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fb47eafdb9'
down_revision: Union[str, None] = '435ab419ca07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'case', 'user', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'case', 'organisation', ['organisation_id'], ['id'])
    op.create_foreign_key(None, 'case', 'user', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_constraint(None, 'case', type_='foreignkey')
    # ### end Alembic commands ###
